# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tae Yeon Hwang
title: Junior Web Developer
email: gxd0214@gmail.com
website: https://github.com/BigHwangTaeYeon/bighwangtaeyeon.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  BigHwangTaeYeon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  중소기업에서 풀스택으로 웹 서비스를 개발/배포/운영을 담당했습니다. 주요 업무를 완료한 후, 제품의 개선이 필요한 부분을 최적화했습니다.<br>
  신기술을 배우고 비효율적인 부분을 개선하는 것을 좋아합니다. 비효율적인 배포 과정을 자동화하여 배포 시스템을 구축한 경험이 있습니다.

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: 제이케이데이터시스템즈
        link: https://archive.gugak.go.kr/
        sub_title: Junior Web Developer
        caption: 2023.04 ~ 2023.12
        description: | # this will include new lines to allow paragraphs
          국악원 아카이브 서비스/관리 시스템 개발/배포/운영<br>
          - 빌드 배포 자동화
          - 프록시 파일 생성 시, 문제 식별 및 개선
          - 전자계약서 솔루션 연계
          - 전자 계약서 연계, 운영 환경에서 NoSuchAlgorithmException 문제 해결
          <br><br>
          기술 스택
            - <mark>전자정부 프레임워크</mark>, <mark>MyBatis</mark>, <mark>Cubrid</mark>
            - <mark>Jenkins</mark>, <mark>SVN</mark>
      - title: 펌프킨
        # link: www.nhncloud.com/kr
        sub_title: Junior Web Developer
        caption: 2022.10 ~ 2023.02
        description: | # this will include new lines to allow paragraphs
          전기차 중전기 제조업체, 통합 관리 시스템 개발<br><br>
          기술 스택
            - <mark>Spring</mark>, <mark>MyBatis</mark>, <mark>MS-SQL</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 빌드 배포 자동화
        # sub_title: Senior Network System Administrator
        # caption: November 2017 - Present
        # quote: >
        #   배포 시, FTP를 통해 class 파일을 직접 올리는 방식을 사용해왔습니다. 휴먼 에러와 개발 비용이 많이 소모되는 것을 확인했습니다.
        description: | # this will include new lines to allow paragraphs
            상황 : 배포 시, FTP를 통해 class 파일을 직접 올리는 방식을 사용해왔습니다. 휴먼 에러와 개발 비용이 많이 소모되는 것을 확인했습니다.<br>
            실행 : 배포 자동화 도구인 Jenkins 를 통해 파이프라인을 구축했습니다. Stage는 빌드 - 백업 - 배포로 구성하였습니다.<br>
            결과 : 빌드 에러를 젠킨스가 알려주고, 많은 시간과 휴먼 에러를 줄일 수 있었습니다.
      - title: 프록시 파일 생성 시, 문제 식별 및 개선
        description: | # this will include new lines to allow paragraphs
            상황 : 영상, 음향, 이미지를 프록시 파일로 경량화하여 서비스합니다. 여러 파일을 생성하는 과정에서 서버가 다운되는 문제가 발견되었습니다.<br>
            실행 : 파일 생성 상태값으로 시작, 생성중, 완료가 있습니다. 상태값을 확인하여 setTimeOut으로 서버에 상태값을 재요청하는 방식으로 동작합니다.<br>
            결과 : 5개의 파일을 진행하면 5개의 상태값을 확인하고 5번 호출을 합니다. 이 과정에서 요청 횟수를 배수로 보내 과부하가 걸리는 것을 확인하였습니다. 일단 상태값을 배열로 담아 한번의 요청만 보내는 것으로 수정하였습니다. 그리고 실시간으로 빠른 리소스의 변경이 필요하다 생각하여 polling websocket 으로 개선하였습니다.

      - title: 전자계약서 솔루션 연계
        description: | # this will include new lines to allow paragraphs
            상황 : 사용자가 계약서를 수기로 작성하여 pdf로 직접 업로드 하였습니다. 솔루션을 통해 전자 서명을 하고 완료 계약서 파일을 자동으로 업로드하는 연계 작업을 진행하였습니다.<br>
            실행 : 계약서 상태 값에 따른 이력 테이블, webhook 이력 테이블, 계약서 파일 테이블을 설계하였습니다. 상태값에 따른 데이터 저장은 스테이트 패턴으로 설계하였습니다. 단일 책임 원칙에 따라 파일 다운로드, 토큰 생성, 토큰 검증, 통신 기능의 Class를 분리하였습니다<br>
            결과 : 전자계약서 상태값에 따라 webhook 이벤트로 정상적으로 테이블에 저장되고, 완료된 계약서 파일이 저장되었습니다.

      - title: 전자 계약서 연계, 운영 환경에서 NoSuchAlgorithmException 문제 해결
        description: | # this will include new lines to allow paragraphs
            상황 : 로컬과 개발 환경에서 테스트를 완료하고 운영 서버에 배포하였습니다. 업체에서 제공하는 코드에서 ECKeyFactory not available 오류가 발생하였습니다.<br>
            실행 : 차이점은 JDK 버전으로 확인하였고 이것을 중심으로 해결책을 찾았습니다. keyFactory class 에 ECKeyFactory 인스턴스를 주입해줘야 사용할 수 있다는 것을 확인하였습니다.<br>
            결과 : 정상적인 작동을 확인하고 업체에서는 그럴리 없다는 답변만 들었던 상황이라 더 확인해본 결과, 썬 마이크로시스템즈가 오라클에 인수되며 해당 JDK는 sun 패키지가 제공되지 않는 것을 확인하고 Oracle에서 sun 패키지는 사용을 추천하지 않는다는 것을 확인하게 되었습니다.

  - title: Side Projects
    layout: list
    content:
      - layout: left
        title: 어떡
        link: https://www.utteok.com https://github.com/Utteok/Type-of-Tteokbokki_Back
        caption: 2024.02 ~ 2024.02
        quote: >
          떡볶이 추천 서비스 백엔드 개발 담당 (기획자 1, 디자인 1, 프론트 1, 백엔드 1)
        description: | # this will include new lines to allow paragraphs
        - Java 언어 Spring 프레임워크로 API 구현
        - 레디스를 활용한 API 캐싱
        - Mybatis -≫ JPA 마이그레이션
        - Jenkins 파이프라인(빌드, 테스트, 배포 환경) 구축
        - TDD 활용
          <br><br>
          기술 스택
            - <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>MariaDB</mark>, <mark>Redis</mark>
            - <mark>Junit5</mark>, <mark>JPA</mark>, <mark>Jenkins</mark>
            - <mark>NCP</mark>, <mark>Nginx</mark>
      - title: 화상채팅
        link: https://github.com/BigHwangTaeYeon/solo
        caption: 2022.10 ~ 2023.02
        quote: >
          랜덤 화상 채팅 서비스 개발
        description: | # this will include new lines to allow paragraphs
          - Java 언어 Spring 프레임워크로 API 및 WebRTC를 P2P 방식으로 구현
          - Redis로 리프레시 토큰 캐싱(인증관련)
          - monolithic -≫ MSA(Spring Cloud) 아키텍쳐 전환
          - Docker
          <br><br>
          기술 스택
            - <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>MariaDB</mark>, <mark>Redis</mark>
            - <mark>Thymeleaf</mark>

  - title: Trouble Shooting
    layout: list
    content:
      - layout: left
        title: 어떡
        link: https://www.utteok.com https://github.com/Utteok/Type-of-Tteokbokki_Back
        description: | # this will include new lines to allow paragraphs
          - 젠킨스 파이프라인
            상황 : 
            실행 : 
            결과 : 
      - title: 화상채팅
        link: https://github.com/BigHwangTaeYeon/solo
        description: | # this will include new lines to allow paragraphs
          - 젠킨스 파이프라인
            상황 : 
            실행 : 
            결과 : 

  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Harvard University
  #       caption: 2010 - 2013
  #       sub_title: BSc Computer Science
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: |
            - <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>Spring</mark>
            - <mark>Spring MVC</mark>, <mark>Spring Security</mark>, <mark>Spring Data JPA/Redis</mark>, <mark>Spring Cloud</mark>
            - <mark>Eclipse</mark>, <mark>Intellij</mark>
      - title: DevOps
        description: |
            - <mark>Cubrid</mark>, <mark>MySql</mark>, <mark>Redis</mark>
            - <mark>Jenkins</mark>, <mark>Git</mark>, <mark>Docker</mark>
      - title: Frontend
        description: |
            - <mark>JSP</mark>, <mark>Java Script</mark>

  # - title: A Little More About Me
  #   layout: text
  #   content: |
  #     - [학습](https://github.com/BigHwangTaeYeon/book_cs)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
